development:
  adapter: postgresql
  database: adela_development
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: adela_test
  encoding: utf8
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: adela_staging
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: adela_production
  encoding: utf8
  pool: 5
  timeout: 5000
